<a href="https://colab.research.google.com/github/ranayash24/MLOps/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.1.0+cu121


##introduction to tensors
creating tensors





In [ ]:
#scalar
scalar =torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2],
                         [3,6],
                         [2,4]]])
TENSOR

tensor([[[1, 2],
         [3, 6],
         [2, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 2])

##Random tensors

why random tensors



In [ ]:
#create a random tensors of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2893, 0.9625, 0.7236, 0.0743],
        [0.0729, 0.8416, 0.0280, 0.4516],
        [0.4059, 0.1804, 0.1983, 0.5816]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))#height,width,colorchenal
random_image_size_tensor.shape,random_image_size_tensor .ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_tensors = torch.rand(2,4,3)
random_tensors

tensor([[[0.9864, 0.1956, 0.5494],
         [0.9790, 0.3005, 0.0819],
         [0.8540, 0.1290, 0.7165],
         [0.0245, 0.0411, 0.2846]],

        [[0.3070, 0.9087, 0.1620],
         [0.5073, 0.4765, 0.9652],
         [0.0961, 0.6467, 0.2914],
         [0.9259, 0.8503, 0.6893]]])

In [ ]:
#create a tensor of all zeors
zero =torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(3,4)
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#Use torch.range()
one_to_ten =torch.arange(start=1,end=10000, step=100)
one_to_ten

tensor([   1,  101,  201,  301,  401,  501,  601,  701,  801,  901, 1001, 1101,
        1201, 1301, 1401, 1501, 1601, 1701, 1801, 1901, 2001, 2101, 2201, 2301,
        2401, 2501, 2601, 2701, 2801, 2901, 3001, 3101, 3201, 3301, 3401, 3501,
        3601, 3701, 3801, 3901, 4001, 4101, 4201, 4301, 4401, 4501, 4601, 4701,
        4801, 4901, 5001, 5101, 5201, 5301, 5401, 5501, 5601, 5701, 5801, 5901,
        6001, 6101, 6201, 6301, 6401, 6501, 6601, 6701, 6801, 6901, 7001, 7101,
        7201, 7301, 7401, 7501, 7601, 7701, 7801, 7901, 8001, 8101, 8201, 8301,
        8401, 8501, 8601, 8701, 8801, 8901, 9001, 9101, 9201, 9301, 9401, 9501,
        9601, 9701, 9801, 9901])

In [ ]:
#creating tensor like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

#dealing with tensor data types

In [ ]:
int_32_tensor = torch.tensor([3,6,8],dtype =torch.long)
int_32_tensor

tensor([3, 6, 8])

##Getting imformation from tensors

'''
Tensors not right datatype -to do geet 'dtype'----> to do get datatype from a tensor, can use 'tensor.dtype'
Tensors not right shape ----> to get shape from a tensor, can use  'tensor.shape'
Tensors not on the right device - to get device from a tensor, can use tensor.device
'''

In [ ]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4034, 0.2125, 0.1460, 0.8854],
        [0.8417, 0.4065, 0.2287, 0.1177],
        [0.7082, 0.5712, 0.5176, 0.3898]])

In [ ]:
#find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'shpe of tensor:{some_tensor.shape}')
print(f'device tensor is on:{some_tensor.device}')

tensor([[0.4034, 0.2125, 0.1460, 0.8854],
        [0.8417, 0.4065, 0.2287, 0.1177],
        [0.7082, 0.5712, 0.5176, 0.3898]])
Datatype of tensor: torch.float32
shpe of tensor:torch.Size([3, 4])
device tensor is on:cpu
